addi        PASSED
add         PASSED
andi        PASSED
and         PASSED
auipc       PASSED
beq         PASSED
bge         PASSED
bgeu        PASSED
blt         PASSED
bltu        PASSED
bne         PASSED
lui         PASSED
ori         PASSED
or          PASSED
rebouclage  PASSED
sll         PASSED
slt         PASSED
sub         PASSED
xori        PASSED
xor         PASSED
